@extends('layouts.dashboard', ['activePage' => 'materials'])
@section('title', 'Materi - Polimicro')
@section('content')
<h1 class="text-2xl font-bold text-slate-900 mb-2">Materi Pembelajaran</h1>
<p class="text-slate-500 mb-6">Akses materi dari mata kuliah yang Anda ikuti</p>
<div class="mb-6"> <select id="filter" class="px-4 py-3 rounded-xl border border-gray-200 bg-white text-sm" onchange="window.location='{{ route('mahasiswa.materials') }}?matkul='+this.value"> <option value="">Semua Mata Kuliah</option> @foreach($enrolled as $m) <option value="{{ $m->id }}" {{ $filterMatkul == $m->id ? 'selected' : '' }}>{{ $m->nama_makul }}</option> @endforeach </select>
</div>
<div class="space-y-4"> @php $filtered = $filterMatkul ? $enrolled->where('id', $filterMatkul) : $enrolled; @endphp @forelse($filtered as $m) @if($m->materi->count() > 0) <div class="card-dashboard overflow-hidden"> <div class="p-5 border-b border-gray-50 flex items-center gap-3"> <div class="w-10 h-10 rounded-xl gradient-primary flex items-center justify-center text-white"><i class="fas fa-book"></i></div> <div><h3 class="font-bold text-slate-900">{{ $m->nama_makul }}</h3><p class="text-xs text-slate-400">{{ $m->materi->count() }} materi tersedia</p></div> </div> <div class="divide-y divide-gray-50"> @foreach($m->materi as $mat) <div class="p-5 hover:bg-cyan-50/50 transition cursor-pointer" onclick="this.querySelector('.detail').classList.toggle('hidden')"> <div class="flex items-center justify-between"> <div class="flex items-center gap-3"> <div class="w-9 h-9 rounded-lg bg-cyan-100 flex items-center justify-center"><i class="fas fa-file-alt text-cyan-600 text-sm"></i></div> <div><p class="font-semibold text-sm">{{ $mat->nama_materi }}</p><p class="text-xs text-slate-400">{{ $mat->created_at->translatedFormat('j F Y') }}</p></div> </div> <i class="fas fa-chevron-down text-gray-300 text-sm"></i> </div> <div class="detail hidden mt-4 p-4 bg-gray-50 rounded-xl text-sm text-gray-600"> <p>{{ $mat->deskripsi_materi }}</p> <div class="mt-3 flex items-center gap-2"> @if($mat->file_materi) <a href="{{ asset('storage/' . $mat->file_materi) }}" target="_blank" class="px-4 py-2 bg-[#0E7490] text-white rounded-lg text-xs font-medium hover:bg-[#155E75] transition inline-flex items-center gap-2"> <i class="fas fa-file-download"></i> {{ basename($mat->file_materi) }} </a> @else <span class="text-xs text-slate-400 italic">Tidak ada file lampiran</span> @endif </div> </div> </div> @endforeach </div> </div> @endif @empty <div class="text-center py-16 text-slate-400"><i class="fas fa-folder-open text-4xl mb-4"></i><p>Belum ada materi tersedia</p></div> @endforelse
</div>
@endsection
